#! /usr/bin/env bash

word="$(shuf /usr/share/dict/words | head -1)"
count="$1"

source=$(google-images-fetch "$word" "$count")
images-to-slideshow "$source"/* "$word.gif"
echo "$word $word.gif"

# November 11th, 2013, Juan Manuel Borges Caño
