#! /usr/bin/env bash

#   |             tw (Translate Word): Human Language Translator            |
#   |           Copyright (C) 2007 - 2014 Juan Manuel Borges Caño           |
#   |                  The need for an smart, fast and rich                 |
#   |               translation answer inspired this command.               |
#   |                     Text Console Language Station                     |

{
	echo "Síntaxis" | colorize bold
	comprueba "$@"
	echo "Traducción" | colorize bold
	traduce "$@"
# No Dictionary For Spanish
	#echo "Definicion" | colorize bold
	#define "$@"
# No Dictionary For Spanish
	echo "(((Pronunciación)))" | colorize bold
	pronuncia "$@"
} | sed -e '/^$/d'
