#! /usr/bin/env bash

#   |             tw (Translate Word): Human Language Translator            |
#   |           Copyright (C) 2007 - 2014 Juan Manuel Borges Caño           |
#   |                  The need for an smart, fast and rich                 |
#   |               translation answer inspired this command.               |
#   |                     Text Console Language Station                     |

{
	echo "Spelling" | colorize bold
	spell "$@"
	echo "Translation" | colorize bold
	translate "$@"
	echo "Definition" | colorize bold
	define "$@"
	echo "(((Pronunciation)))" | colorize bold
	pronounce "$@"
} | sed -e '/^$/d'
